### ISSUE TITLE
typo in German tooltips and help file

### ISSUE THREAD

**Issue by frase-git** [cmb69/calendar_xh#17]
> Einstellung der resultierende Beite der Eintragstabelle

**Comment by frase-git** [comment]
In help_de.htm:
> Die Veranstaltungsliste sollte auf der Veranstaltungsseite (event page), die in den Spracheinstellungen von Calendar_XH gewählt wurde, durch den folgenden Pluginaufruf **einbettet** werden:

= eingebettet

> Usage

= Verwendung

**Comment by cmb69** [comment]
Danke!
