### ISSUE TITLE
Replace headings with table captions

### ISSUE THREAD

**Issue by frase-git** [cmb69/calendar_xh#48]
`<h2>` as headings for calendar sections are probably fine in most cases - but not always. They might interfere with the page structure. Especially the month selection for the calendar itself as `<h2>` is very inconvenient.

Maybe no heading tag should be used there at all? About the CSS they are well designable.
Or selectable in the configuration?

**Comment by cmb69** [comment]
Well, yeah, that's a big mess. Unfortunately, they didn't implement proper sectioning; otherwise could simply use `<h1>` (pre HTML5 browsers are not an issue for me anyway). I don't like *not* using a heading here (since it is a heading), so I will make that configurable.

**Comment by cmb69** [comment]
Stupid me! There is actually no need for heading elements at all, since we can use a table caption instead, what appears to be even more semantical.

**Comment by frase-git** [comment]
> table caption

This idea is even better.
