### ISSUE TITLE
Scrolling text horizontal (marquee)

### ISSUE THREAD

**Issue by frase-git** [cmb69/calendar_xh#49]
If you want to make the scrolling text horizontal (which works well with CSS), the hardcoded `<br>` in the source text disturbs considerably.
`<div class="nextevent_date">... <br>...</div>`

Is that not possible somehow differently? Without?

I have a dream.
Configuration option for the scrolling text: vertical or horizontal.
But that would be luxury and not mandatory ;-)

**Comment by cmb69** [comment]
Yes, that `<br>` is ugly. Probably the two parts of long events (language text and end/start date) should be wrapped inside `<div>`s. The rest should be doable via CSS.

> But that would be luxury and not mandatory ;-)

Yep. :)
