### ISSUE TITLE
marquee shows the location as ### for birthdays

### ISSUE THREAD

**Issue by frase-git** [cmb69/calendar_xh#51]
See the heading.

**Comment by cmb69** [comment]
Oops, I think you're right. Thanks for reporting!

**Comment by frase-git** [comment]
I have tested https://github.com/cmb69/calendar_xh/commit/9138041944271498ba9e03cf2b0145c49ceb48dc and it seems to fix the problem.
However, the debud mode reports when calling a page with "marquee":

> NOTICE: Undefined index: location
> ... \plugins\calendar\classes\View.php:36
> 

I am not quite sure if I have done everything correctly. Could you check this?

**Comment by frase-git** [comment]
It seems to me that my previous post has taken care of itself.
Let's forget about it ;-).

**Comment by cmb69** [comment]
Oops, totally overlooked this, but if it is resolved, fine. :)
